name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    name: Build guestbook-service
    steps:
    - uses: actions/checkout@v2
    - name: Build container
      run: cat ~/rebuild.sh | bash
